version: "3"
services:
  server:
    image: leonelaguirre/ldae-sims-server:latest
    build:
      context: .
      target: final
    env_file:
      - ./.env
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - progresDB:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  progresDB:

